Hello everyone, this is the pull request for the rating functionality.
motaz99/chatgpt-devs-era pull request #40
Opened 2023-07-19 19:12 UTC by harethriyadh

2023-07-19 22:12 UTC, ozlemkeles requested changes
Good work Harith, but there are a few things we need to discuss before merging

2023-07-19 22:12 UTC, ozlemkeles commented on src/controllers/authController.js
why did you make changes in authController? Isn't your task about rating?

2023-07-19 22:12 UTC, ozlemkeles commented on src/models/User.js
> +    required: false,
why did you add these required: false lines? if you don't provide required it will be not required as a default

2023-07-19 22:12 UTC, ozlemkeles commented on src/controllers/dishController.js
> +};
I think we should move this inside the client controller. We can create new endpoint in client routes such as 
router.post('/dishes/:id/rateDish', clientController.rateDish);
there we can rate a dish and control that;
- only clients can rate the dishes
- a client can rate a dish one time only, cause clients shouldn't be able change the rate of the same dish

2023-07-20 06:46 UTC, harethriyadh commented on src/controllers/authController.js
ok...

2023-07-20 14:48 UTC, closed without merging

2023-07-23 17:32 UTC, motaz99 commented
@harethriyadh, why did you close this PR?